# Generated by Django 5.2 on 2025-05-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='spellList',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
