# Generated by Django 5.2 on 2025-05-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0002_alter_spell_spelllist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='spell',
            name='spellList',
        ),
        migrations.AddField(
            model_name='spell',
            name='spellList',
            field=models.ManyToManyField(to='spells.spelllist'),
        ),
    ]
