# Generated by Django 5.2 on 2025-05-28 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0004_rename_spelllist_spelllists'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpellLists',
            new_name='SpellList',
        ),
    ]
