# Generated by Django 5.2 on 2025-05-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0005_rename_spelllists_spelllist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellList2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spell2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('spellLevelType', models.CharField(blank=True, max_length=255, null=True)),
                ('castingTime', models.CharField(blank=True, max_length=50, null=True)),
                ('spellRange', models.CharField(blank=True, max_length=50, null=True)),
                ('components', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('spellList', models.ManyToManyField(to='spells.spelllist')),
            ],
        ),
    ]
