# Generated by Django 5.2 on 2025-05-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0006_spelllist2024_spell2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell2024',
            name='spellList',
            field=models.ManyToManyField(to='spells.spelllist2024'),
        ),
    ]
