# Generated by Django 5.2 on 2025-06-18 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0007_alter_spell2024_spelllist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spell',
            new_name='Spell2014',
        ),
        migrations.RenameModel(
            old_name='SpellList',
            new_name='SpellList2014',
        ),
    ]
