# Generated by Django 5.2 on 2025-07-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0008_rename_spell_spell2014_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell2014',
            old_name='spellLevelType',
            new_name='spellLevel',
        ),
        migrations.RenameField(
            model_name='spell2024',
            old_name='spellLevelType',
            new_name='spellLevel',
        ),
        migrations.AddField(
            model_name='spell2014',
            name='spellSchool',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='spell2024',
            name='spellType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
