# Generated by Django 5.2 on 2025-07-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0009_rename_spellleveltype_spell2014_spelllevel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell2024',
            old_name='spellType',
            new_name='spellSchool',
        ),
        migrations.AlterField(
            model_name='spell2024',
            name='spellList',
            field=models.ManyToManyField(to='spells.spelllist2014'),
        ),
    ]
