# Generated by Django 5.2 on 2025-07-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0010_rename_spelltype_spell2024_spellschool_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('spellLevel', models.CharField(blank=True, max_length=255, null=True)),
                ('spellSchool', models.CharField(blank=True, max_length=255, null=True)),
                ('castingTime', models.CharField(blank=True, max_length=50, null=True)),
                ('spellRange', models.CharField(blank=True, max_length=50, null=True)),
                ('components', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(max_length=50)),
                ('spellKey', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='spell2014',
            name='spellList',
        ),
        migrations.RemoveField(
            model_name='spell2024',
            name='spellList',
        ),
        migrations.DeleteModel(
            name='SpellList2024',
        ),
        migrations.RenameModel(
            old_name='SpellList2014',
            new_name='SpellList',
        ),
        migrations.AddField(
            model_name='spells',
            name='spellList',
            field=models.ManyToManyField(to='spells.spelllist'),
        ),
        migrations.DeleteModel(
            name='Spell2014',
        ),
        migrations.DeleteModel(
            name='Spell2024',
        ),
    ]
